name: shopswift
description: "A new Flutter project."
publish_to: 'none'  # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  equatable: ^2.0.0
  get: ^4.3.8
  intl: ^0.19.0
  image_picker: ^1.0.7
  flutter_staggered_grid_view: ^0.7.0
  path: ^1.8.3
  cloud_firestore: ^4.14.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  firebase_core: ^2.24.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_auth: ^4.16.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  http:
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
